export enum Author {
  FIRST_AUTHOR = "FIRST_AUTHOR",
  CO_FIRST_AUTHOR = "CO_FIRST_AUTHOR",
  CORRESPONDING_AUTHOR = "CORRESPONDING_AUTHOR",
  FIRST_CORRESPONDING_AUTHOR = "FIRST_CORRESPONDING_AUTHOR",
  CO_AUTHOR = "CO_AUTHOR",
}
