export enum Performance {
  SCI = "SCI",
  SCOPUS = "SCOPUS",
  SCIE = "SCIE",
  INTERNATIONAL_B = "INTERNATIONAL_B",
  DOMESTIC_A = "DOMESTIC_A",
  DOMESTIC_B = "DOMESTIC_B",
  ICOP = "ICOP",
  ICP = "ICP",
  DCOP = "DCOP",
  DCP = "DCP",
  IPR = "IPR",
  IPA = "IPA",
  DPR = "DPR",
  DPA = "DPA",
}
